# Resampling Methods - Lab

## Introduction

Now that you have some preliminary background on bootstrapping, jackknife, and permutation tests, its time to practice those skills by coding them into functions. You'll then apply these tests to a hypothesis test and compare the results to a parametric t-test.

## Objectives

In this lab you will: 

* Create functions that perform resampling techniques and use them on datasets

## Bootstrap sampling


Bootstrap sampling works by combining two distinct samples into a universal set and generating random samples from this combined sample space in order to compare these random splits to the two original samples. The idea is to see if the difference between the two **original** samples is statistically significant. If similar differences can be observed through the random generation of samples, then the observed differences are not actually significant.


Write a function to perform bootstrap sampling. The function should take in two samples A and B. The two samples need not be the same size. From this, create a universal sample by combining A and B. Then, create a resampled universal sample of the same size using random sampling with replacement. Finally, split this randomly generated universal set into two samples which are the same size as the original samples, A and B. The function should return these resampled samples.

Example:

```python

A = [1,2,3]
B = [2,2,5,6]

Universal_Set = [1,2,2,2,3,5,6]
Resampled_Universal_Set = [6, 2, 3, 2, 1, 1, 2] # Could be different (randomly generated with replacement)

Resampled_A = [6,2,3]
Resampled_B = [2,1,1,2]
```

In [61]:
import numpy as np

In [62]:
A = [1,2,3]
B = [2,2,5,6]
Universal_Set = A + B
Universal_Set

[1, 2, 3, 2, 2, 5, 6]

In [63]:
Resampled_Universal_Set = np.random.choice(Universal_Set, len(Universal_Set), replace = True)
Resampled_Universal_Set

array([2, 3, 5, 1, 1, 2, 2])

In [64]:
Resample_A = Resampled_Universal_Set[:3]
Resample_A

array([2, 3, 5])

In [65]:
Resample_B = Resampled_Universal_Set[3:]
Resample_B

array([1, 1, 2, 2])

In [66]:
def bootstrap(A, B):
    # Your code here
    Universal_Set = A + B
    Resampled_Universal_Set = np.random.choice(Universal_Set, len(Universal_Set), replace = True)
    Resample_A = Resampled_Universal_Set[:len(A)]
    Resample_B = Resampled_Universal_Set[len(A):]
    return Resample_A, Resample_B

In [67]:
bootstrap(A, B)

(array([2, 2, 1]), array([1, 2, 3, 2]))

## Jackknife 

Write a function that creates additional samples by removing one element at a time. The function should do this for each of the `n` items in the original sample, returning `n` samples, each with `n-1` members.

In [68]:
Universal_Set

[1, 2, 3, 2, 2, 5, 6]

In [69]:
Universal_Set[1:]

[2, 3, 2, 2, 5, 6]

In [70]:
Universal_Set[:1] + Universal_Set[2:]

[1, 3, 2, 2, 5, 6]

In [71]:
Universal_Set[:2] + Universal_Set[3:]

[1, 2, 2, 2, 5, 6]

In [72]:
for i in range(len(Universal_Set)):
    print(i)

0
1
2
3
4
5
6


In [73]:
for i in range(len(Universal_Set)):
    print(Universal_Set[:i])

[]
[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 2]
[1, 2, 3, 2, 2]
[1, 2, 3, 2, 2, 5]


In [74]:
for i in range(len(Universal_Set)):
    print(Universal_Set[:i] + Universal_Set[i+1:])

[2, 3, 2, 2, 5, 6]
[1, 3, 2, 2, 5, 6]
[1, 2, 2, 2, 5, 6]
[1, 2, 3, 2, 5, 6]
[1, 2, 3, 2, 5, 6]
[1, 2, 3, 2, 2, 6]
[1, 2, 3, 2, 2, 5]


In [75]:
def jack1(sample):
    """This function should take in a list of n observations and return n lists
    each with one member (presumably the nth) removed."""
    # Your code here
    samples = []
    for i in range(len(sample)):
        new_sample = sample[:i] + sample[i + 1:]
        samples.append(new_sample)
    return samples

In [76]:
jack1(Universal_Set)

[[2, 3, 2, 2, 5, 6],
 [1, 3, 2, 2, 5, 6],
 [1, 2, 2, 2, 5, 6],
 [1, 2, 3, 2, 5, 6],
 [1, 2, 3, 2, 5, 6],
 [1, 2, 3, 2, 2, 6],
 [1, 2, 3, 2, 2, 5]]

## Permutation testing

Define a function that generates all possible, equally sized, two set splits of two sets A and B. Sets A and B need not be the same size, but all of the generated two set splits should be of equal size. For example, if we had a set with 5 members and a set with 7 members, the function would return all possible 5-7 ordered splits of the 12 items.

> Note that these are actually combinations! However, as noted previously, permutation tests really investigate possible regroupings of the data observations, so calculating combinations is a more efficient approach!


Here's a more in depth example:

```python
A = [1, 2, 2]
B = [1, 3]
combT(A, B) 
[([1,2,2], [1,3]),
 ([1,2,3], [1,2]),
 ([1,2,1], [2,3]),
 ([1,1,3], [2,2]),
 ([2,2,3], [1,1])]
               
```  

These are all the possible 3-2 member splits of the 5 elements: 1, 1, 2, 2, 3. 

In [77]:
A = [1, 2, 2]
B = [1, 3]

In [78]:
from itertools import combinations

In [79]:
combinations(A + B, 3)

In [80]:
A + B

[1, 2, 2, 1, 3]

In [81]:
for x in combinations(A + B, 3):
    print(x)

(1, 2, 2)
(1, 2, 1)
(1, 2, 3)
(1, 2, 1)
(1, 2, 3)
(1, 1, 3)
(2, 2, 1)
(2, 2, 3)
(2, 1, 3)
(2, 1, 3)


In [82]:
sorted(A + B) #in order

[1, 1, 2, 2, 3]

In [83]:
for x in combinations(sorted(A + B), 3): #sorting is important
    print(x)

(1, 1, 2)
(1, 1, 2)
(1, 1, 3)
(1, 2, 2)
(1, 2, 3)
(1, 2, 3)
(1, 2, 2)
(1, 2, 3)
(1, 2, 3)
(2, 2, 3)


In [84]:
set(sorted(A + B)) #remove duplicates

{1, 2, 3}

In [85]:
for x in combinations(set(sorted(A + B)), 3):
    print(x)

(1, 2, 3)


In [86]:
for x in set(combinations(sorted(A + B), 3)): 
    print(x)

(2, 2, 3)
(1, 1, 3)
(1, 2, 3)
(1, 1, 2)
(1, 2, 2)


In [87]:
for x in set(combinations(sorted(A + B), 3)): 
    both_lists = (A + B).copy() #so we don't change their values
    for val in x:
        both_lists.remove(val)
    print(x, both_lists)

(2, 2, 3) [1, 1]
(1, 1, 3) [2, 2]
(1, 2, 3) [2, 1]
(1, 1, 2) [2, 3]
(1, 2, 2) [1, 3]


In [88]:
def combT(a,b):
    # Your code here
    my_list = []
    for x in set(combinations(sorted(a + b), len(a))): 
        both_lists = (a + b).copy()
        for val in x:
            both_lists.remove(val)
        my_list.append((list(x), both_lists))
    return my_list

In [89]:
combT(A, B)

[([2, 2, 3], [1, 1]),
 ([1, 1, 3], [2, 2]),
 ([1, 2, 3], [2, 1]),
 ([1, 1, 2], [2, 3]),
 ([1, 2, 2], [1, 3])]

## Permutation testing in Practice
Let's further investigate the scenario proposed in the previous lesson. Below are two samples A and B. The samples are mock data for the blood pressure of sample patients. The research study is looking to validate whether there is a statistical difference in the blood pressure of these two groups using a 5% significance level.  First, calculate the mean blood pressure of each of the two samples. Then, calculate the difference of these means. From there, use your `combT()` function, defined above, to generate all the possible combinations of the entire sample data into A-B splits of equivalent sizes as the original sets. For each of these combinations, calculate the mean blood pressure of the two groups and record the difference between these sample means. The full collection of the difference in means between these generated samples will serve as the denominator to calculate the p-value associated with the difference between the original sample means.

For example, in our small handwritten example above:

$\mu_a = \frac{1+2+2}{3} = \frac{5}{3}$  
and  
$\mu_b = \frac{1+3}{2} = \frac{4}{2} = 2$  

Giving us

$\mu_a - \mu_b = \frac{5}{3} - 2 = \frac{1}{2}$

In comparison, for our various combinations we have:

([1,2,2], [1,3]):  $\mu_a - \mu_b = \frac{5}{3} - 2 = \frac{1}{2}$  
([1,2,3], [1,2]):  $\mu_a - \mu_b = 2 - \frac{3}{2} = \frac{1}{2}$  
([1,2,1], [2,3]):  $\mu_a - \mu_b = \frac{4}{3} - \frac{5}{3} = -\frac{1}{2}$  
([1,1,3], [2,2]):  $\mu_a - \mu_b = \frac{5}{3} - 2 = \frac{1}{2}$  
([2,2,3], [1,1]):  $\mu_a - \mu_b = \frac{7}{3} - 1 = \frac{4}{3}$  

A standard hypothesis test for this scenario might be:

$H_0: \mu_a = \mu_b$  
$H_1: \mu_a < \mu_b$  
  
Thus comparing our sample difference to the differences of our possible combinations, we look at the number of experiments from our combinations space that were the same or greater than our sample statistic, divided by the total number of combinations. In this case, 4 out of 5 of the combination cases produced the same or greater differences in the two sample means. This value .8 is a strong indication that we cannot refute the null hypothesis for this instance.

In [90]:
a = [109.6927759 , 120.27296943, 103.54012038, 114.16555857,
       122.93336175, 110.9271756 , 114.77443758, 116.34159338,
       112.66413025, 118.30562665, 132.31196515, 117.99000948]
b = [123.98967482, 141.11969004, 117.00293412, 121.6419775 ,
       123.2703033 , 123.76944385, 105.95249634, 114.87114479,
       130.6878082 , 140.60768727, 121.95433026, 123.11996767,
       129.93260914, 121.01049611]

In [99]:
diff_a_b = np.mean(b) - np.mean(a)
diff_a_b

8.049348947857169

In [93]:
np.mean(a), np.mean(b)

(116.15997700999999, 124.20932595785716)

In [95]:
# Your code here
# ⏰ Expect your code to take several minutes to run
my_combs = combT(a, b)

In [96]:
len(my_combs)

9657700

In [100]:
counter = 0
for progress, (ac, bc) in enumerate(my_combs):
    if (progress > 0) & (progress % 100000 == 0):
        print(progress)
    comb_diff = np.mean(bc) - np.mean(ac)
    if comb_diff > diff_a_b:
        counter += 1

100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
2400000
2500000
2600000
2700000
2800000
2900000
3000000
3100000
3200000
3300000
3400000
3500000
3600000
3700000
3800000
3900000
4000000
4100000
4200000
4300000
4400000
4500000
4600000
4700000
4800000
4900000
5000000
5100000
5200000
5300000
5400000
5500000
5600000
5700000
5800000
5900000
6000000
6100000
6200000
6300000
6400000
6500000
6600000
6700000
6800000
6900000
7000000
7100000
7200000
7300000
7400000
7500000
7600000
7700000
7800000
7900000
8000000
8100000
8200000
8300000
8400000
8500000
8600000
8700000
8800000
8900000
9000000
9100000
9200000
9300000
9400000
9500000
9600000


In [101]:
counter / len(my_combs)

0.010923718897874236

## T-test revisited

The parametric statistical test equivalent to our permutation test above would be a t-test of the two groups. Perform a t-test on the same data above in order to calculate the p-value. How does this compare to the above results?

In [102]:
# Your code here
from scipy.stats import ttest_ind
ttest_ind(a, b) #one-tail test

Ttest_indResult(statistic=-2.4279196935987, pvalue=0.023053215321495863)

In [103]:
ttest_ind(a, b)[1] / 2 #two-tail test

0.011526607660747932

## Bootstrap applied

Use your code above to apply the bootstrap technique to this hypothesis testing scenario. Here's a pseudo-code outline for how to do this:

1. Compute the difference between the sample means of A and B
2. Initialize a counter for the number of times the difference of the means of resampled samples is greater then or equal to the difference of the means of the original samples
3. Repeat the following process 10,000 times:
    1. Use the bootstrap sampling function you used above to create new resampled versions of A and B 
    2. Compute the difference between the means of these resampled samples 
    3. If the difference between the means of the resampled samples is greater then or equal to the original difference, add 1 the counter you created in step 2
4. Compute the ratio between the counter and the number of simulations (10,000) that you performed
    > This ratio is the percentage of simulations in which the difference of sample means was greater than the original difference

In [104]:
diff_a_b

8.049348947857169

In [107]:
# Your code here
counter = 0
for i in range(10000):
    ab, bb = bootstrap(a, b)
    bootstrap_diff = np.mean(bb) - np.mean(ab)
    if bootstrap_diff > diff_a_b:
        counter += 1
print(counter / 10000)

0.013


## Summary

Well done! In this lab, you practice coding modern statistical resampling techniques of the 20th century! You also started to compare these non-parametric methods to other parametric methods such as the t-test that we previously discussed.